# 2D Array Slicing And Indexing


In [3]:
import numpy as np

y = np.arange(42).reshape(6,7)

y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41]])

In [4]:
y[0]

array([0, 1, 2, 3, 4, 5, 6])

In [5]:
y[2]

array([14, 15, 16, 17, 18, 19, 20])

## Returning column columns can be a bit tricky.



In [6]:
y[:, 0]


array([ 0,  7, 14, 21, 28, 35])

In [7]:
y[:, 3]


array([ 3, 10, 17, 24, 31, 38])

## Output One Element Only



In [8]:
y[2, 3]


17

### Get first three elements of second column.



In [9]:
y[0:3, 1]


array([ 1,  8, 15])