# Numpy array using zeros() and ones()

### In this video we will discuss how to create a Numpy array of different shapes and initialized with 0 & 1.



# numpy.zeros()

##### Python’s Numpy module provides a function to create a numpy array of given shape & type and all values in it initialized with 0’s



# numpy.zeros(shape, dtype=float, order='C')

#####  Arguments:

##### shape : Shape of the numpy array. Single int or sequence of int.
##### dtype : (Optional) Data type of elements. Default is float64.
##### order : (Optional) Order in which data is stored in multi-dimension array i.e. in row major(‘F’) or column major (‘C’). Default is ‘C’.


In [5]:
import numpy as np 

#It will create a 2D numpy array of ints filled with zeros.

arr = np.zeros((3, 3) , dtype=np.int64)
print('Contents of the Numpy Array : \n', arr)



Contents of the Numpy Array : 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [8]:
arr.shape

(3, 4)

# numpy.ones()

#### Python’s Numpy module provides a function to create a numpy array of given shape & type and all values in it initialized with 1’s

## numpy.ones(shape, dtype=float, order='C')
##### Arguments:

##### shape : Shape of the numpy array. Single int or sequence of int.
##### dtype : (Optional) Data type of elements. Default is float64.
##### order : (Optional) Order in which data is stored in multi-dimension array i.e. in row major(‘F’) or column major (‘C’). Default is ‘C’.

In [7]:
# create a 2D numpy array with 3 rows &amp; 4 columns filled with 1's and int data type

arr = np.ones((3, 4) , dtype=np.int64)

print('Contents of the Numpy Array : \n', arr)

Contents of the Numpy Array : 
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [9]:
type(arr)

numpy.ndarray

In [10]:
arr.shape

(3, 4)