# reshape() in numpy

### Change the shape of the array without disturbing the data.


In [1]:
import numpy as np

a=np.array([[0,1],[2,3],[5,6]])

print('Original Array : \n')
a

Original Array : 



array([[0, 1],
       [2, 3],
       [5, 6]])

In [2]:
a.shape


(3, 2)

In [4]:
# Let's reshape the array a

a_ = a.reshape((2,3))

print('After reshape operation : \n')

print(a_, a_.shape)

After reshape operation : 

[[0 1 2]
 [3 5 6]] (2, 3)


In [5]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [6]:
a.shape


(3,)

In [7]:
a.ndim


1

In [8]:
a_ = a.reshape((-1,1))
a_

array([[1],
       [2],
       [3]])

In [9]:
a_.shape


(3, 1)

In [10]:
a_.ndim


2