# NumPy - Broadcasting


#### The term broadcasting refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations. Arithmetic operations on arrays are usually done on corresponding elements. If two arrays are of exactly the same shape, then these operations are smoothly performed.



In [2]:
import numpy as np 

a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a * b 
print(c)

[ 10  40  90 160]


### Broadcasting is possible if the following rules are satisfied −

#### Array with smaller ndim than the other is prepended with '1' in its shape.

#### Size in each dimension of the output shape is maximum of the input sizes in that dimension.

#### An input can be used in calculation, if its size in a particular dimension matches the output size or its value is exactly 1.

#### If an input has a dimension size of 1, the first data entry in that dimension is used for all calculations along that dimension.

In [7]:
import numpy as np 
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])  

print ('First array:' )
print(a) 
   
print('Second array:' )

print(b)
   
print('First Array + Second Array' )
print(a + b)

First array:
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]
Second array:
[1. 2. 3.]
First Array + Second Array
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]
